"""change ip_address and mac_address to string types

Revision ID: 001
Revises: 
Create Date: 2024-08-07 11:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE devices ALTER COLUMN ip_address TYPE VARCHAR(45)')
    op.execute('ALTER TABLE devices ALTER COLUMN mac_address TYPE VARCHAR(17)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE devices ALTER COLUMN ip_address TYPE INET USING ip_address::INET')
    op.execute('ALTER TABLE devices ALTER COLUMN mac_address TYPE MACADDR USING mac_address::MACADDR')
    # ### end Alembic commands ###
